export const inventory = [
  {
    skuNumber: 1,
    itemName: "Boots",
    price: 115.65,
    quantityInStock: 3,
    inStock: true,
    category: "Apparel",
  },
  {
    skuNumber: 2,
    itemName: "Socks",
    price: 15.12,
    quantityInStock: 2,
    inStock: true,
    category: "Apparel",
  },
  {
    skuNumber: 3,
    itemName: "Jacket",
    price: 120.81,
    quantityInStock: 1,
    inStock: true,
    category: "Apparel",
  },
  {
    skuNumber: 4,
    itemName: "T-Shirt",
    price: 85.91,
    quantityInStock: 2,
    inStock: true,
    category: "Apparel",
  },
  {
    skuNumber: 5,
    itemName: "Gloves",
    price: 25.08,
    quantityInStock: 3,
    inStock: true,
    category: "Apparel",
  },
  {
    skuNumber: 6,
    itemName: "Shorts",
    price: 35.43,
    quantityInStock: 1,
    inStock: true,
    category: "Apparel",
  },
  {
    skuNumber: 7,
    itemName: "Pants",
    price: 80.84,
    quantityInStock: 2,
    inStock: true,
    category: "Apparel",
  },
  {
    skuNumber: 8,
    itemName: "Hat",
    price: 15.72,
    quantityInStock: 1,
    inStock: true,
    category: "Apparel",
  },
];
// export const inventory = [
//   {
//     id: 1,
//     skuNumber: 1,
//     itemName: "Boots",
//     price: 115.65,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 2,
//     skuNumber: 1,
//     itemName: "Boots",
//     price: 115.65,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 3,
//     skuNumber: 1,
//     itemName: "Boots",
//     price: 115.65,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 4,
//     skuNumber: 1,
//     itemName: "Boots",
//     price: 115.65,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 5,
//     skuNumber: 1,
//     itemName: "Boots",
//     price: 115.65,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 6,
//     skuNumber: 2,
//     itemName: "Socks",
//     price: 15.12,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 7,
//     skuNumber: 3,
//     itemName: "Jacket",
//     price: 120.81,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 8,
//     skuNumber: 4,
//     itemName: "T-Shirt",
//     price: 85.91,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 9,
//     skuNumber: 4,
//     itemName: "T-Shirt",
//     price: 85.91,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 10,
//     skuNumber: 5,
//     itemName: "Gloves",
//     price: 25.08,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 11,
//     skuNumber: 6,
//     itemName: "Shorts",
//     price: 35.43,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 12,
//     skuNumber: 6,
//     itemName: "Shorts",
//     price: 35.43,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 13,
//     skuNumber: 7,
//     itemName: "Pants",
//     price: 80.84,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 14,
//     skuNumber: 7,
//     itemName: "Pants",
//     price: 80.84,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 15,
//     skuNumber: 7,
//     itemName: "Pants",
//     price: 80.84,
//     inStock: true,
//     category: "Apparel",
//   },
//   {
//     id: 16,
//     skuNumber: 8,
//     itemName: "Hat",
//     price: 15.72,
//     inStock: true,
//     category: "Apparel",
//   },
// ];
